Cart/urls.py
# endregion

# __init__.py
import sys
import os
import time
import datetime
import json
import logging
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'Cart'

urlpatterns = [
    # path('', (views.Index), name='Index'),
    path('', (views.Index), name='Index'),
    path('payment/', (views.PayMent), name='payment'),


]
# End of TFile

Home/urls.py
import sys
import os
import time
import datetime
import json
import logging
from django.urls import path
from . import views

app_name = 'Home'

urlpatterns = [
     # path('contact/', (views.ContactView), name='ContactView'),
     path('', (views.IndexView), name='IndexView'),
     path('login/', (views.LoginView), name='login'),
     path('registers/', (views.RegistersView), name='registers'),
     path('logout/', (views.logout_view), name='logout_view'),
     path('profile/', (views.profile_view), name='profile_view'),
     path('change_password/', (views.change_password), name='change_password'),
]

coolmate/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Home.urls', namespace='Home')),
    path('contact/', include('Contact.urls', namespace='Contact')),
    path('cart/', include('Cart.urls', namespace='Cart')),
    # path('Blog/', include('Blog.urls', namespace='Blog')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Cart/models.py
from django.db import models

# Create your models here.
# from django.db import models
# from django.core.validators import MinValueValidator, MaxValueValidator
#
#
# class Payment(models.Model):
#     method = models.CharField(max_length=255, null=False, blank=False)
#     is_active = models.BooleanField(default=True)
#     des = models.TextField(default='')
#
#
# class Order(models.Model):
#     status_choice = (
#         (0, 'Đang chờ phê duyệt'),
#         (1, 'Chờ lấy hàng'),
#         (2, 'Đang giao'),
#         (3, 'Đã giao đến người dùng')
#     )
#     user = models.ForeignKey('user.User', on_delete=models.CASCADE)
#     tax = models.PositiveSmallIntegerField(default=0.1)
#     status = models.PositiveSmallIntegerField(choices=status_choice, default=0)
#     price_ship = models.DecimalField(max_digits=10, decimal_places=2, validators=[MinValueValidator(0)], default=1.5)
#     receiving_address = models.TextField(null=False, blank=False)
#     discount = models.DecimalField(max_digits=10, decimal_places=2, null=False, blank=False, default=0)
#     total_price = models.FloatField(null=False, blank=False, validators=[MinValueValidator(0)])
#     payment = models.ForeignKey(Payment, on_delete=models.SET_NULL, null=True, default=1)
#     created_at = models.DateTimeField(auto_now_add=True)
#     updated_at = models.DateTimeField(auto_now=True)
#
#     class Meta:
#         ordering = ['-created_at']
#
#     def __str__(self):
#         return self.user.username
#
#
# class OrderItem(models.Model):
#     product = models.ForeignKey('products.Product', on_delete=models.CASCADE, null=False, blank=False, )
#     order = models.ForeignKey(Order, models.CASCADE, null=False, blank=False, related_name='orderitem')
#     quantity = models.PositiveIntegerField(default=1)
#     active = models.BooleanField(default=True)
#     des = models.TextField(default='')
#
#     def __str__(self):
#         return self.product.name
#
#
# class Cart(models.Model):
#     status_choice = (
#         (0, 'not working'),
#         (1, 'working')
#     )
#     user = models.OneToOneField('user.User', on_delete=models.CASCADE, primary_key=True)
#     status = models.PositiveSmallIntegerField(choices=status_choice, default=1)
#     des = models.TextField(default='')
#
#     def __str__(self):
#         return self.user
#
#
# class CartItem(models.Model):
#     product = models.ForeignKey('products.Product', on_delete=models.CASCADE, null=False, blank=False)
#     cart = models.ForeignKey(Cart, models.CASCADE, null=False, blank=False)
#     quantity = models.PositiveIntegerField(default=1)
#     active = models.BooleanField(default=True)
#     discount = models.DecimalField(max_digits=10, decimal_places=2, null=False, blank=False, default=0)
#     des = models.TextField(default='')
#     created_at = models.DateTimeField(auto_now_add=True)
#     updated_at = models.DateTimeField(auto_now=True)
#
#     def __str__(self):
#         return self.product.name

Cart/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader

from django.db.models import Q
# Create your views here.
from .models import *
# from PortalMgmt.views import DefaultContext as dContext


def Index(request):
    context = {}
    # all_about = AboutContent.objects.all()
    # context['all_about'] = all_about
    template = loader.get_template(str('Cart/index.html'))
    return HttpResponse(template.render(context, request))


from django.shortcuts import render

from Home.views import IndexViewContext as dContext


def Index(request):
    context = dContext()
    template = loader.get_template(str('Cart/index.html'))
    return HttpResponse(template.render(context, request))

# Create your views here.
def PayMent(request):
    context = dContext()
    template = loader.get_template(str('Cart/payment.html'))
    return HttpResponse(template.render(context, request))

Cart/templates/Cart/index.html
<<<<<<< HEAD
=======
{% extends "Home/base.html" %}

>>>>>>> 3c4e0268a1b11e3396dd6cc732c042453b3051fe
{% load i18n %}
{% load tz %}
{% load static %}
    <!-- end header -->
{% block content %}
<<<<<<< HEAD
    <main role="main">
=======
    <main role="main" style="margin-top:150px">
>>>>>>> 3c4e0268a1b11e3396dd6cc732c042453b3051fe
        <!-- Block content - Đục lỗ trên giao diện bố cục chung, đặt tên là `content` -->
        <div class="container mt-4">
            <div id="thongbao" class="alert alert-danger d-none face" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>

            <h1 class="text-center">Giỏ hàng</h1>
            <div class="row">
                <div class="col col-md-12">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>STT</th>
                                <th>Ảnh đại diện</th>
                                <th>Tên sản phẩm</th>
                                <th>Số lượng</th>
                                <th>Đơn giá</th>
                                <th>Thành tiền</th>
                                <th>Hành động</th>
                            </tr>
                        </thead>
                        <tbody id="datarow">
                            <tr>
                                <td>1</td>
                                <td>
                                    <img src="{% static 'Cart/assets/img/product/ipad4.png' %}" class="hinhdaidien">
                                </td>
                                <td>Apple Ipad 4 Wifi 16GB</td>
                                <td class="text-right">2</td>
                                <td class="text-right">11,800,000.00</td>
                                <td class="text-right">23,600,000</td>
                                <td>
                                    <!-- Nút xóa, bấm vào sẽ xóa thông tin dựa vào khóa chính `sp_ma` -->
                                    <a id="delete_1" data-sp-ma="2" class="btn btn-danger btn-delete-sanpham">
                                        <i class="fa fa-trash" aria-hidden="true"></i> Xóa
                                    </a>
                                </td>
                            </tr>
                            <tr>
                                <td>2</td>
                                <td>
                                    <img src="{% static 'Cart/assets/img/product/nokia-asha-311.jpg' %}" class="hinhdaidien">
                                </td>
                                <td>Nokia Asha 311</td>
                                <td class="text-right">4</td>
                                <td class="text-right">2,699,000.00</td>
                                <td class="text-right">1,0796,000</td>
                                <td>
                                    <!-- Nút xóa, bấm vào sẽ xóa thông tin dựa vào khóa chính `sp_ma` -->
                                    <a id="delete_2" data-sp-ma="6" class="btn btn-danger btn-delete-sanpham">
                                        <i class="fa fa-trash" aria-hidden="true"></i> Xóa
                                    </a>
                                </td>
                            </tr>
                            <tr>
                                <td>3</td>
                                <td>
                                    <img src="{% static 'Cart/assets/img/product/iphone5-white.jpeg' %}" class="hinhdaidien">
                                </td>
                                <td>Apple iPhone 5 16GB White</td>
                                <td class="text-right">8</td>
                                <td class="text-right">1,4990,000.00</td>
                                <td class="text-right">119,920,000</td>
                                <td>
                                    <!-- Nút xóa, bấm vào sẽ xóa thông tin dựa vào khóa chính `sp_ma` -->
                                    <a id="delete_3" data-sp-ma="4" class="btn btn-danger btn-delete-sanpham">
                                        <i class="fa fa-trash" aria-hidden="true"></i> Xóa
                                    </a>
                                </td>
                            </tr>
                        </tbody>
                    </table>

                    <a href="{% url 'Home:IndexView' %}" class="btn btn-warning btn-md"><i class="fa fa-arrow-left"
                            aria-hidden="true"></i>&nbsp;Quay
                        về trang chủ</a>
                    <a href="{% url 'Cart:payment' %}" class="btn btn-primary btn-md"><i
                            class="fa fa-shopping-cart" aria-hidden="true"></i>&nbsp;Thanh toán</a>
                </div>
            </div>
        </div>
        <!-- End block content -->
    </main>

    <!-- footer -->
    <footer class="footer mt-auto py-3">
        <div class="container">
<<<<<<< HEAD
            <span>Bản quyền © bởi <a href="https://nentang.vn">Nền Tảng</a> - <script>document.write(new Date().getFullYear());</script>.</span>
=======
            <span>Bản quyền © bởi <a href="https://thangnv.w3spaces.com/">Thangnv</a> - <script>document.write(new Date().getFullYear());</script>.</span>
>>>>>>> 3c4e0268a1b11e3396dd6cc732c042453b3051fe
            <span class="text-muted">Hành trang tới Tương lai</span>

            <p class="float-right">
                <a href="#">Về đầu trang</a>
            </p>
        </div>
    </footer>
    <!-- end footer -->

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="{% static 'Cart/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'Cart/vendor/popperjs/popper.min.js' %}"></script>
    <script src="{% static 'Cart/vendor/bootstrap/js/bootstrap.min.js' %}"></script>

    <!-- Custom script - Các file js do mình tự viết -->
    <script src="{% static 'Cart/assets/js/app.js' %}"></script>
{% endblock %}

Cart/templates/Cart/payment.html
{% extends "Home/base.html" %}

{% load i18n %}
{% load tz %}
{% load static %}

{% block content %}

<head>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'Cart/vendor/bootstrap/css/bootstrap.min.css' %}" type="text/css">
    <!-- Font awesome -->
    <link rel="stylesheet" href="{% static 'Cart/vendor/font-awesome/css/font-awesome.min.css' %}" type="text/css">

    <!-- Custom css - Các file css do chúng ta tự viết -->
    <link rel="stylesheet" href="{% static 'Cart/assets/css/app.css' %}" type="text/css' %}">
</head>

<bo

    <main role="main" style="margin-top:150px">
        <!-- Block content - Đục lỗ trên giao diện bố cục chung, đặt tên là `content` -->
        <div class="container mt-4" >
            <form class="needs-validation" name="frmthanhtoan" method="post"
                action="#">
                <input type="hidden" name="kh_tendangnhap" value="dnpcuong">

                <div class="py-5 text-center" style="margin-top:150px">
                    <i class="fa fa-credit-card fa-4x" aria-hidden="true"></i>
                    <h2>Thanh toán</h2>
                    <p class="lead">Vui lòng kiểm tra thông tin Khách hàng, thông tin Giỏ hàng trước khi Đặt hàng.</p>
                </div>

                <div class="row">
                    <div class="col-md-4 order-md-2 mb-4">
                        <h4 class="d-flex justify-content-between align-items-center mb-3">
                            <span class="text-muted">Giỏ hàng</span>
                            <span class="badge badge-secondary badge-pill">2</span>
                        </h4>
                        <ul class="list-group mb-3">
                            <input type="hidden" name="sanphamgiohang[1][sp_ma]" value="2">
                            <input type="hidden" name="sanphamgiohang[1][gia]" value="11800000.00">
                            <input type="hidden" name="sanphamgiohang[1][soluong]" value="2">

                            <li class="list-group-item d-flex justify-content-between lh-condensed">
                                <div>
                                    <h6 class="my-0">Apple Ipad 4 Wifi 16GB</h6>
                                    <small class="text-muted">11800000.00 x 2</small>
                                </div>
                                <span class="text-muted">23600000</span>
                            </li>
                            <input type="hidden" name="sanphamgiohang[2][sp_ma]" value="4">
                            <input type="hidden" name="sanphamgiohang[2][gia]" value="14990000.00">
                            <input type="hidden" name="sanphamgiohang[2][soluong]" value="8">

                            <li class="list-group-item d-flex justify-content-between lh-condensed">
                                <div>
                                    <h6 class="my-0">Apple iPhone 5 16GB White</h6>
                                    <small class="text-muted">14990000.00 x 8</small>
                                </div>
                                <span class="text-muted">119920000</span>
                            </li>
                            <li class="list-group-item d-flex justify-content-between">
                                <span>Tổng thành tiền</span>
                                <strong>143520000</strong>
                            </li>
                        </ul>


                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Mã khuyến mãi">
                            <div class="input-group-append">
                                <button type="submit" class="btn btn-secondary">Xác nhận</button>
                            </div>
                        </div>

                    </div>
                    <div class="col-md-8 order-md-1">
                        <h4 class="mb-3">Thông tin khách hàng</h4>

                        <div class="row">
                            <div class="col-md-12">
                                <label for="kh_ten">Họ tên</label>
                                <input type="text" class="form-control" name="kh_ten" id="kh_ten"
                                    value="Dương Nguyễn Phú Cường" readonly="">
                            </div>
                            <div class="col-md-12">
                                <label for="kh_gioitinh">Giới tính</label>
                                <input type="text" class="form-control" name="kh_gioitinh" id="kh_gioitinh" value="Nam"
                                    readonly="">
                            </div>
                            <div class="col-md-12">
                                <label for="kh_diachi">Địa chỉ</label>
                                <input type="text" class="form-control" name="kh_diachi" id="kh_diachi"
                                    value="130 Xô Viết Nghệ Tỉnh" readonly="">
                            </div>
                            <div class="col-md-12">
                                <label for="kh_dienthoai">Điện thoại</label>
                                <input type="text" class="form-control" name="kh_dienthoai" id="kh_dienthoai"
                                    value="0915659223" readonly="">
                            </div>
                            <div class="col-md-12">
                                <label for="kh_email">Email</label>
                                <input type="text" class="form-control" name="kh_email" id="kh_email"
                                    value="phucuong@ctu.edu.vn" readonly="">
                            </div>
                            <div class="col-md-12">
                                <label for="kh_ngaysinh">Ngày sinh</label>
                                <input type="text" class="form-control" name="kh_ngaysinh" id="kh_ngaysinh"
                                    value="11/6/1989" readonly="">
                            </div>
                            <div class="col-md-12">
                                <label for="kh_cmnd">CMND</label>
                                <input type="text" class="form-control" name="kh_cmnd" id="kh_cmnd" value="362209685"
                                    readonly="">
                            </div>
                        </div>

                        <h4 class="mb-3">Hình thức thanh toán</h4>

                        <div class="d-block my-3">
                            <div class="custom-control custom-radio">
                                <input id="httt-1" name="httt_ma" type="radio" class="custom-control-input" required=""
                                    value="1">
                                <label class="custom-control-label" for="httt-1">Tiền mặt</label>
                            </div>
                            <div class="custom-control custom-radio">
                                <input id="httt-2" name="httt_ma" type="radio" class="custom-control-input" required=""
                                    value="2">
                                <label class="custom-control-label" for="httt-2">Chuyển khoản</label>
                            </div>
                            <div class="custom-control custom-radio">
                                <input id="httt-3" name="httt_ma" type="radio" class="custom-control-input" required=""
                                    value="3">
                                <label class="custom-control-label" for="httt-3">Ship COD</label>
                            </div>
                        </div>
                        <hr class="mb-4">
                        <button class="btn btn-primary btn-lg btn-block" type="submit" name="btnDatHang">Đặt
                            hàng</button>
                    </div>
                </div>
            </form>

        </div>
        <!-- End block content -->
    </main>

    <!-- footer -->
    <footer class="footer mt-auto py-3">
        <div class="container">
            <span>Bản quyền © bởi <a href="https://nentang.vn">Nền Tảng</a> - <script>document.write(new Date().getFullYear());</script>.</span>
            <span class="text-muted">Hành trang tới Tương lai</span>

            <p class="float-right">
                <a href="#">Về đầu trang</a>
            </p>
        </div>
    </footer>
    <!-- end footer -->

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="{% static 'Cart/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'Cart/vendor/popperjs/popper.min.js' %}"></script>
    <script src="{% static 'Cart/vendor/bootstrap/js/bootstrap.min.js' %}"></script>

    <!-- Custom script - Các file js do mình tự viết -->
    <script src="{% static 'Cart/assets/js/app.js' %}"></script>

</body>

{% endblock %}