Cart/urls.py
# endregion

# __init__.py
import sys
import os
import time
import datetime
import json
import logging
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'Cart'

urlpatterns = [
    # path('', (views.Index), name='Index'),
    path('', (views.Index), name='Index'),
    path('payment/', (views.PayMent), name='payment'),


]
# End of TFile

Home/urls.py
import sys
import os
import time
import datetime
import json
import logging
from django.urls import path
from . import views

app_name = 'Home'

urlpatterns = [
     # path('contact/', (views.ContactView), name='ContactView'),
     path('', (views.IndexView), name='IndexView'),
     path('login/', (views.LoginView), name='login'),
     path('registers/', (views.RegistersView), name='registers'),
     path('logout/', (views.logout_view), name='logout_view'),
     path('profile/', (views.profile_view), name='profile_view'),
     path('change_password/', (views.change_password), name='change_password'),
]

coolmate/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Home.urls', namespace='Home')),
    path('contact/', include('Contact.urls', namespace='Contact')),
    path('cart/', include('Cart.urls', namespace='Cart')),
    # path('Blog/', include('Blog.urls', namespace='Blog')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Home/models.py
import random
import string

from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from django.utils.timezone import now as djnow


# Create your models here.

class Menu(models.Model):
    name = models.CharField(max_length=1024,
                            null=True,
                            blank=True)
    title = models.CharField(max_length=1024,
                             null=True,
                             blank=True)
    url = models.CharField(max_length=1024,
                           null=True,
                           blank=True)

    parent_menu = models.ForeignKey("self",
                                    null=True,
                                    blank=True,
                                    on_delete=models.CASCADE)
    icon = models.ImageField(max_length=4096,
                             null=True,
                             blank=True)
    ico_class = models.CharField(max_length=1024,
                                 null=True,
                                 blank=True)

    css_class = models.CharField(max_length=1024,
                                 null=True,
                                 blank=True)
    order = models.IntegerField(default=0)
    created_at = models.DateTimeField(default=djnow,
                                      null=False)
    updated_at = models.DateTimeField(default=djnow,
                                      null=False)

    def __str__(self):
        if self.parent_menu is None:
            return str(self.name)
        else:
            return str("[%s] %s" % (self.parent_menu.name, self.name))

    def admin_name(self):
        if self.parent_menu is None:
            return str(self.name)
        else:
            return str("[%s] %s" % (self.parent_menu.name, self.name))

    def sub_menus(self):
        result = Menu.objects.filter(parent_menu=self).order_by('order')
        if len(result) == 0:
            return None
        else:
            return result

    def save(self, *args, **kwargs):
        self.updated_at = djnow()
        super().save(*args, **kwargs)
    #
    # def ll_str(self):
    #     result = "Test"
    #     if self.name != "" and self.name is not None:
    #         result = self.name
    #     return result


AUTH_USER_MODEL = getattr(settings, 'AUTH_USER_MODEL', 'auth.User')


# upload_storage = FileSystemStorage(location=settings.MEDIA_ROOT, base_url='/media')
def rand_slug():
    return ''.join(random.choice(string.ascii_letters + string.digits) for _ in range(10))


from datetime import datetime
import os


def _upload_to(instance, filename):
    result = os.path.join(instance._meta.app_label, instance.__class__.__name__, datetime.today().strftime("%Y/%m/%d"),
                          filename)
    print('result = %s' % result)
    return result


class UserProfile(models.Model):
    choice_gender = (
        ('Not known', 'Not known'),
        ('Male', 'Male'),
        ('Female', 'Female'),
        ('Not applicable', 'Not applicable')
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=1024,
                            null=True,
                            blank=True)
    avatar = models.ImageField(null=True,
                               blank=True,
                               upload_to=_upload_to
                               )
    gender = models.CharField(null=True,
                              max_length=1024,
                              choices=choice_gender,
                              default='Not known')
    date_of_birth = models.DateField(null=True,
                                     blank=True)
    phone = models.CharField(max_length=45,
                             null=True,
                             blank=True)
    biography = models.TextField(null=True,
                                 blank=True)
    email = models.EmailField(max_length=255,
                              null=True,
                              blank=True)
    created_at = models.DateTimeField(default=djnow,
                                      null=False)
    updated_at = models.DateTimeField(default=djnow,
                                      null=False)

    def __str__(self):
        return str(self.name)

Home/forms.py
import re

from django import forms
from django.contrib.auth.forms import UserCreationForm, SetPasswordForm
from django.contrib.auth.models import User

class LoginForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder" : "Username",
                "class": "form-control"
            }
        ))
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder" : "Password",
                "class": "form-control"
            }
        ))

class SignUpForm(UserCreationForm):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder" : "Username",
                "class": "form-control"
            }
        ))
    name1 = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Name",
                "class": "form-control"
            }
        ),
        required=False,
    )
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={
                "placeholder" : "Email",
                "class": "form-control"
            }
        ))
    password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder" : "Password",
                "class": "form-control"
            }
        ))
    password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder" : "Password check",
                "class": "form-control"
            }
        ))

    class Meta:
        model = User
        fields = ('username', 'name1', 'email', 'password1', 'password2')



class PasswordChangeForm(SetPasswordForm):
    """
    A form that lets a user change their password by entering their old
    password.
    """
    error_messages = dict(SetPasswordForm.error_messages, **{
        'password_incorrect': ("Your old password was entered incorrectly. Please enter it again."),
    })
    old_password = forms.CharField(
        label=("Old password"),
        strip=False,
        widget=forms.PasswordInput(attrs={'autofocus': True}),
    )

    field_order = ['old_password', 'new_password1', 'new_password2']

    def clean_old_password(self):
        """
        Validates that the old_password field is correct.
        """
        old_password = self.cleaned_data["old_password"]
        if not self.user.check_password(old_password):
            raise forms.ValidationError(
                self.error_messages['password_incorrect'],
                code='password_incorrect',
            )
        return old_password

Home/views.py
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.core.checks import messages
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.template import loader
from django.db.models import Q
from django.views.decorators.csrf import csrf_exempt
from django.contrib import messages
# from Home.models import *
# Create your views here.

# Create your views here.
from .forms import LoginForm, SignUpForm
from .models import *
# from .views import IndexViewContext as dContext

def IndexView(request):
    context = {}
    all_menus = Menu.objects.filter(parent_menu=None).order_by('parent_menu', 'order')
    context['all_menus'] = all_menus

    all_sub_menus = Menu.objects.filter(~Q(parent_menu=None)).order_by('parent_menu', 'order')
    context['all_sub_menus'] = all_sub_menus

    template = loader.get_template(str('Home/index.html'))
    return HttpResponse(template.render(context, request))

def IndexViewContext():
    context = {}
    all_menus = Menu.objects.filter(parent_menu=None).order_by('parent_menu', 'order')
    context['all_menus'] = all_menus

    all_sub_menus = Menu.objects.filter(~Q(parent_menu=None)).order_by('parent_menu', 'order')
    context['all_sub_menus'] = all_sub_menus

    return context


@csrf_exempt
def ContactView(request):
    context = {}
    all_menus = Menu.objects.filter(parent_menu=None).order_by('parent_menu', 'order')
    context['all_menus'] = all_menus

    all_sub_menus = Menu.objects.filter(~Q(parent_menu=None)).order_by('parent_menu', 'order')
    context['all_sub_menus'] = all_sub_menus

    print(request)
    if request.POST:
        print(request.POST)

        content = request.POST['test-input']
        new_menu = Menu.objects.create(name=content,
                                       title=content)
    template = loader.get_template(str('Home/index.html'))
    return HttpResponse(template.render(context, request))


def LoginView(request):
    form = LoginForm(request.POST or None)

    msg = None

    if request.method == "POST":

        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                try:
                    u_profile = username.objects.filter(user=user).first()
                    if u_profile is not None:
                        u_profile.last_login_at = djnow()
                        u_profile.save()
                except Exception as xx:
                    print("[LoginView] Exception: %s" % str(xx))
                return redirect("/")
                # check type of user direct
            else:
                msg = '<b>Tên tài khoản</b> hoặc <b>Mật khẩu</b> không đúng!'
        else:
            msg = 'Thông tin không hợp lệ'

    return render(request, "Home/login.html", {"form": form, "msg": msg})



def RegistersView(request):
    msg = None
    success = False
    if request.method == "POST":
        print("todo: Tạo user")
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get("username")
            raw_password = form.cleaned_data.get("password1")
            user = authenticate(username=username, password=raw_password)
            if user is None:
                print("Tạo user thất bại")
            else:
                print("Tạo user thành công")
            msg = 'Đã thêm mới tài khoản - hãy <a href="/login">Đăng nhập</a>.'
            success = True
            print("bạn đã đăng ký thành công")
            return redirect("/login/")

        else:
            msg = 'Thông tin không hợp lệ'
    else:
        form = SignUpForm()

    return render(request, "Home/registers.html", {"form": form, "msg": msg, "success": success})




def logout_view(request):
    logout(request)
    return redirect('/')


def profile_view(request):
    context = {}
    user_rq = request.user
    print(user_rq.username)
    all_menus = Menu.objects.filter(parent_menu=None).order_by('parent_menu', 'order')
    context['all_menus'] = all_menus

    all_sub_menus = Menu.objects.filter(~Q(parent_menu=None)).order_by('parent_menu', 'order')
    context['all_sub_menus'] = all_sub_menus
    profile = UserProfile.objects.filter(user=user_rq)
    context['profile'] = profile
    template = loader.get_template(str('Home/profile.html'))
    return HttpResponse(template.render(context, request))


def change_password(request):
    context = IndexViewContext()
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!')
            return redirect('/login')
        else:
            messages.error(request, 'Please correct the error below.')

    else:
        form = PasswordChangeForm(request.user)

    context["form"] = form
    # template = loader.get_template(str('Home/change_password.html'))

    return render( request, 'Home/change_password.html',context)
    # return HttpResponse(template.render(context, request))

Home/templates/Home/base.html
{% load static %} {% load i18n %} {% load tz %}
<html lang="en">

<head>
    <title>Cool Mate</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="Cool Mate Template">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'Home/plugins/font-awesome-4.7.0/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" href="{% static 'Home/styles/bootstrap4/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'Home/plugins/OwlCarousel2-2.2.1/owl.carousel.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'Home/plugins/OwlCarousel2-2.2.1/owl.theme.default.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'Home/plugins/OwlCarousel2-2.2.1/animate.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'Home/styles/main_styles.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'Home/styles/responsive.css' %}">
</head>
{% include 'Home/header.html' %}
<body>
<main>
    {% block content %} {% endblock %}

 {% include 'Home/footer.html' %}
    </main>


<script src="{% static 'Home/js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'Home/styles/bootstrap4/popper.js' %}"></script>
<script src="{% static 'Home/styles/bootstrap4/bootstrap.min.js' %}"></script>
<script src="{% static 'Home/plugins/Isotope/isotope.pkgd.min.js' %}"></script>
<script src="{% static 'Home/plugins/OwlCarousel2-2.2.1/owl.carousel.js' %}"></script>
<script src="{% static 'Home/plugins/easing/easing.js' %}"></script>
<script src="{% static 'Home/js/custom.js' %}"></script>
</body>

</html>

Home/templates/Home/change_password.html
{% extends "Home/base.html" %}

{% load i18n %}
{% load tz %}
{% load static %}

{% block content %}
    <html lang="en">
    <head>
	<title>Sign - in</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->
	<link rel="icon" type="image/png" href="{% static 'Home/login2/images/icons/favicon.ico' %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'Home/login2/vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'Home/login2/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'Home/login2/fonts/Linearicons-Free-v1.0.0/icon-font.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'Home/login2/vendor/animate/animate.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'Home/login2/vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'Home/login2/vendor/animsition/css/animsition.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'Home/login2/vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'Home/login2/vendor/daterangepicker/daterangepicker.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'Home/login2/css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'Home/login2/css/main.css' %}">
<!--===============================================================================================-->
</head>
<body>

	<div class="limiter" style="margin-top: 100px;">
		<div class="container-login100">
			<div class="wrap-login100">
				<div class="login100-form-title" style="background-image: url(../../static/Home/login2/images/bg-01.jpg);">
					<span class="login100-form-title-1">
						Change Password
					</span>
					<p>	{% if msg %}
							<h4 class="text-danger"> {{ msg | safe }} </h4>
						{% else %}

						{% endif %}
					</p>
				</div>

				<form class="login100-form validate-form"  method="post" action="">
                    {% csrf_token %}
					<div class="wrap-input100 validate-input m-b-26" data-validate="Password is required">
						<div>
							<span class="label-input100">Old Password</span>
							{{ form.old_password }}
						</div>
						<span class="text-error"></span>
						{{ form.old_password.errors }}
					</div>

					<div class="wrap-input100 validate-input m-b-26" data-validate = "Password is required">
						<div>
							<span class="label-input100">New Password</span>
							{{ form.new_password1 }}
						</div>
						<span class="text-error"></span>
						{{ form.new_password1.errors }}

					</div>
					<div class="wrap-input100 validate-input m-b-26" data-validate = "Password is required">
						<div>
							<span class="label-input100">Enter New Password</span>
							{{ form.new_password2 }}
						</div>
						<span class="text-error"></span>
						{{ form.new_password2.errors }}
					</div>


					<div class="container-login100-form-btn">
						<button id="btnSave" class="login100-form-btn" type="submit">
							Save
						</button>
					</div>
				</form>
				<div>
					<p class="mb-2 text-muted" style="text-align: center" >
						<br /> &copy; <a target="_blank" rel="noopener" href="#" class="f-w-400">Thangnv</a> -
						<a target="_blank" rel="noopener" href="" class="f-w-400">1621050733@student.humg.edu.vn</a>
					</p>
				</div>
			</div>
		</div>
	</div>

	<script src="{% static 'Home/js/changePassword.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'Home/login2/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'Home/login2/vendor/animsition/js/animsition.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'Home/login2/vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'Home/login2/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'Home/login2/vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'Home/login2/vendor/daterangepicker/moment.min.js' %}"></script>
	<script src="{% static 'Home/login2/vendor/daterangepicker/daterangepicker.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'Home/login2/vendor/countdowntime/countdowntime.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'Home/login2/js/main.js' %}"></script>

</body>
</html>
{% endblock %}

Home/templates/Home/footer.html
{% load static %}
{% load i18n %}
{% load tz %}
<footer class="footer">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <div class="footer_nav_container d-flex flex-sm-row flex-column align-items-center justify-content-lg-start justify-content-center text-center">
                        <ul class="footer_nav">
                            <li><a href="#">Blog</a></li>
                            <li><a href="#">FAQs</a></li>
                            <li><a href="contact.html">Contact us</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="footer_social d-flex flex-row align-items-center justify-content-lg-end justify-content-center">
                        <ul>
                            <li><a href="https://www.facebook.com/profile.php?id=100009199475224"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                            <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                            <li><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                            <li><a href="https://web.skype.com/live:.cid.41c59bfc35cf5fd2"><i class="fa fa-skype" aria-hidden="true"></i></a></li>
                            <li><a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="footer_nav_container">
                        <div class="cr">©2021 All Rights Reserverd. Made with <i class="fa fa-heart-o"
                                                                                 aria-hidden="true"></i> by <a href="#">Thangnv</a>
                            </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>

Home/templates/Home/header.html
{% load static %} {% load i18n %} {% load tz %}


<header class="header trans_300">

        <!-- Top Navigation -->

        <div class="top_nav">
            <div class="container">
                <div class="row">
                    <div class="col-md-6">
                        <div class="top_nav_left">free shipping on all u.s orders over $50</div>
                    </div>
                    <div class="col-md-6 text-right">
                        <div class="top_nav_right">
                            <ul class="top_nav_menu">

                                <!-- Currency / Language / My Account -->

                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Main Navigation -->

        <div class="main_nav_container">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12 text-right">
                        <div class="logo_container">
                            <a href="/">Cool<span>Mate</span></a>
                        </div>
                        <nav class="navbar">
                            <ul class="navbar_menu">
                                {% for menu in all_menus %}
                                    <li><a href="{{ menu.url }}">{{ menu.title}}</a>
                                    {% if menu.sub_menus %}
                                        <ul class="submenu">
                                            {% for sub_menu in menu.sub_menus %}
                                                <li><a href="{{ sub_menu.url }}">{{ sub_menu.title }}</a></li>
                                            {% endfor %}
                                        </ul>
                                    {% endif %}

                                    </li>
                                {% endfor %}
                            </ul>
                            <ul class="navbar_user">
                                <li><a href="#"><i class="fa fa-search" aria-hidden="true"></i></a></li>
                                {% if request.user.is_authenticated %}
                                    <li><a href="{% url 'Home:profile_view' %}"><i class="fa fa-user-circle-o" aria-hidden="true"></i></a></li>
                                    <li><a href="{% url 'Home:logout_view' %}"><i class="fa fa-sign-out" aria-hidden="true"></i></a></li>
                                    <li><a href="{% url 'Home:change_password' %}"><i class="fa fa-edit" aria-hidden="true"></i></a></li>
                                {% else %}
                                    <li><a href="{% url 'Home:login' %}"><i class="fa fa-user" aria-hidden="true"></i></a></li>
                                {% endif %}
                                <li class="checkout">
                                    <a href="{% url 'Cart:Index' %}">
                                        <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                                        <span id="checkout_items" class="checkout_items">2</span>
                                    </a>
                                </li>
                            </ul>
                            <div class="hamburger_container">
                                <i class="fa fa-bars" aria-hidden="true"></i>
                            </div>
                        </nav>
                    </div>
                </div>
            </div>
        </div>

    </header>